name: customer
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1
  dotted_border: ^3.1.0
  flutter_html: ^3.0.0
  photo_view: ^0.15.0
  bottom_picker: ^4.1.1
  timelines_plus: ^1.0.8
  badges: ^3.1.2
  in_app_review: ^2.0.11
  dropdown_textfield: ^1.2.0

  # State Management
  get: ^4.7.3
  provider: ^6.1.5+1

  # Network & Storage
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  path: ^1.9.1

  # Firebase & Notifications
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  firebase_database: ^12.1.0
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

  # Authentication / User
  country_code_picker: ^3.4.1
  pin_code_fields: ^8.0.1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # Maps & Location
  google_maps_flutter: ^2.14.0
  flutter_osm_plugin: ^1.4.3
  osm_nominatim: ^4.0.1
  geolocator: any
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.1.0
  map_launcher: ^4.4.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  location: ^8.0.1

  # Media
  image_picker: ^1.2.1
  video_player: ^2.10.1
  video_compress: ^3.1.4

  # Sharing & QR
  share_plus: ^12.0.1
  qr_flutter: ^4.1.0
  qr_code_dart_scan: ^0.11.5
  clipboard: ^2.0.2

  # Payment
  flutter_stripe: ^12.1.1
  razorpay_flutter: ^1.4.0
  flutter_paypal: ^0.2.1

  # Utilities
  mailer: ^6.6.0
  googleapis_auth: ^2.0.0
  date_picker_timeline: ^1.2.7
  sqflite: ^2.4.2
  intl: ^0.20.2
  uuid: ^4.5.2
  flutter_google_places_hoc081098: ^2.0.0

dependency_overrides:
  webview_flutter: ^4.9.0
  http: ^1.6.0
  google_api_headers: ^5.0.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/

  fonts:
    - family: EssentialSans
      fonts:
        - asset: assets/fonts/essential_sans_Regular.otf
          weight: 600
        - asset: assets/fonts/essential_sans_medium.otf
          weight: 500
        - asset: assets/fonts/essential_sans_semi_bold.otf
          weight: 600
        - asset: assets/fonts/essential_sans_bold.otf
          weight: 700
